import { MarkerType } from '@xyflow/react'

export const roles = {
  commercial: { label: 'Comercial', color: '#5376db' },
  management: { label: 'Gerencia', color: '#9570ce' },
  operations: { label: 'Operaciones', color: '#d99832' },
  system: { label: 'Sistema', color: '#24998b' },
  external: { label: 'Externo', color: '#718096' },
  admin: { label: 'Administrador', color: '#c2577f' },
}

function node(id, title, subtitle, role, x, y, details, extra = {}) {
  return {
    id, type: 'diagram', position: { x, y },
    ariaLabel: `${title}. ${roles[role].label}. ${subtitle}`,
    data: { title, subtitle, role, details, ...extra },
  }
}

function edge(source, target, label = '', extra = {}) {
  return {
    id: `${source}-${target}`, source, target, label, type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed, color: '#8899ad' },
    style: { stroke: '#8899ad', strokeWidth: 1.5 },
    labelStyle: { fill: '#475569', fontSize: 11, fontWeight: 600 },
    labelBgStyle: { fill: '#f8fafc', fillOpacity: 0.96 },
    labelBgPadding: [7, 5], labelBgBorderRadius: 5,
    ...extra,
  }
}

const priceRules = [
  'Margen de servicios: un porcentaje único por CSP-Tenant, aplicado a todas sus ventas.',
  'Margen de utilidad: porcentaje configurable por producto.',
  'Ambos porcentajes se calculan sobre el costo: precio final = costo + (costo × % servicios / 100) + (costo × % utilidad / 100).',
  'Importes en USD, redondeados a máximo dos decimales. No se incluyen impuestos.',
]

const orderRules = [
  'Un pedido pertenece a un cliente y a un solo proveedor. Nunca mezcla proveedores.',
  'Puede incluir varios CSP-Tenants del mismo cliente y proveedor, todos en estado Activo.',
  'Cada línea/producto está vinculada a exactamente un CSP-Tenant.',
  'El pedido completo contiene solo productos nuevos o solo productos asociados a suscripciones activas; no se pueden mezclar, incluso entre CSP-Tenants.',
  'Nuevo significa que ese CSP-Tenant no tiene una suscripción asociada a ese producto.',
]

export const diagrams = [
  {
    id: 'overview', navTitle: 'Visión general', navSubtitle: 'Componentes y responsabilidades',
    title: 'Una arquitectura, un recorrido completo',
    description: 'Clientes, proveedores y CSP-Tenants conectados por un proceso comercial con controles claros.',
    takeaway: 'Del cliente a la suscripción',
    highlights: [
      'Comercial prepara; Gerencia autoriza excepciones de margen; Operaciones valida la documentación.',
      'Los servicios automáticos actualizan el catálogo y aprovisionan por CSP-Tenant.',
      'Selecciona los componentes para saltar a sus diagramas de detalle.',
    ],
    nodes: [
      node('erp', 'ERP', 'Consulta externa por NIT', 'external', 0, 0, ['Es el origen vigente de los datos del cliente.', 'Sin respuesta válida no se crea el cliente.'], { related: 'lifecycle' }),
      node('legacy', 'Oportunidades', 'Estudio → aprobación → cliente', 'commercial', 0, 210, ['Ruta histórica que se retirará.', 'La oportunidad aprobada puede convertirse en cliente.'], { deprecated: true, related: 'lifecycle' }),
      node('client', 'Cliente', 'Un cliente · múltiples CSP-Tenants', 'system', 350, 90, ['Si ya existe por NIT, se reutiliza: no se crea de nuevo.', 'Puede tener varios CSP-Tenants por proveedor, segmento o fecha de corte.'], { related: 'lifecycle' }),
      node('tenant', 'CSP-Tenant', 'Exclusivo de un cliente y proveedor', 'commercial', 700, 90, ['Comercial lo crea desde el sistema en uno de tres orígenes: nuevo, existente bajo otro distribuidor o existente creado fuera de la plataforma.', 'Tiene segmentos (Comercial, Educación, Gobierno, Sin ánimo de lucro) y estados; Operaciones lo valida y lo activa.', 'Debe estar Activo para participar en pedidos.', ...priceRules], { related: 'csptenant' }),
      node('provider', 'Proveedor', 'Catálogo y mínimos de margen', 'external', 350, 410, ['Distribuidor autorizado de uno o más proveedores.', 'Cada proveedor define mínimos configurables de servicios y utilidad.', 'Productos: licencias, servicios, hardware u otros.']),
      node('catalog', 'Catálogo sincronizado', 'Actualización automática background', 'system', 700, 410, ['Los servicios background incorporan y actualizan los productos del proveedor en la base de datos del sistema.', 'No es una carga manual ni sincronización de suscripciones.', 'Cada producto tiene segmento (Comercial, Educación o Gobierno) y un estado: Activo, Descontinuado, Inactivo o Inconsistente.'], { related: 'products' }),
      node('order', 'Pedido', 'Un cliente · un proveedor · varios CSP', 'commercial', 1050, 90, orderRules, { related: 'orders' }),
      node('controls', 'Controles del pedido', 'Márgenes → documentos → Operaciones', 'operations', 1400, 90, ['Gerencia aprueba dentro del sistema solo cuando se requiere por márgenes globales inferiores a los mínimos.', 'Operaciones valida documentos, productos, cantidades, costos y precios finales; no aprueba márgenes.'], { related: 'orders' }),
      node('provision', 'Aprovisionamiento', 'Compras separadas por CSP-Tenant', 'system', 1750, 90, ['Comienza desde el estado Por Aplicar.', 'Resultados: Aprovisionado, Error Envio o Aplicado Parcial.'], { related: 'provisioning' }),
      node('subscriptions', 'Suscripciones', 'Consulta y sincronización bajo demanda', 'system', 1050, 410, ['Se sincronizan al entrar al detalle del CSP-Tenant.', 'Cantidades y fechas de inicio y fin son consultables.'], { related: 'subscriptions' }),
      node('contacts', 'Contactos del CSP-Tenant', 'Información de referencia', 'commercial', 1400, 410, ['Pertenecen al CSP-Tenant, no al pedido.', 'No autorizan compras ni participan en aprobaciones.'], { related: 'subscriptions' }),
    ],
    edges: [
      edge('erp', 'client', 'Datos válidos'), edge('legacy', 'client', 'Legado', { style: { stroke: '#8899ad', strokeDasharray: '6 5' } }),
      edge('client', 'tenant', '1 → N'), edge('provider', 'catalog', 'Background'),
      edge('tenant', 'order', 'Activo'), edge('catalog', 'order', 'Productos'),
      edge('order', 'controls', 'Validaciones'), edge('controls', 'provision', 'Por Aplicar'),
      edge('tenant', 'subscriptions', 'Detalle CSP'), edge('tenant', 'contacts', 'Referencia', { sourceHandle: 'bottom', targetHandle: 'top' }),
    ],
  },
  {
    id: 'lifecycle', navTitle: 'Cliente & CSP-Tenant', navSubtitle: 'Origen, exclusividad y activación',
    title: 'Un origen confiable para cada cliente',
    description: 'El ERP valida el registro; Comercial crea los CSP-Tenants que conectan al cliente con cada proveedor.',
    takeaway: 'Sin datos válidos, no hay alta',
    highlights: ['Reutilizar al cliente existente evita duplicados.', 'Un CSP-Tenant no puede compartirse entre clientes ni proveedores.', 'Varios CSP-Tenants pueden responder a segmentos o fechas de corte diferentes.'],
    nodes: [
      node('nit', 'Buscar cliente por NIT', '¿Existe en el sistema?', 'commercial', 0, 0, ['La consulta identifica si el cliente ya está registrado.', 'Si existe, no se vuelve a crear.']),
      node('erp-check', 'Consultar ERP', 'Solo para un cliente no registrado', 'external', 340, 190, ['El ERP trae los datos necesarios para registrar un cliente real.', 'Esta ruta no pasa por oportunidades.']),
      node('blocked', 'Alta bloqueada · error', 'NIT no encontrado o servicio fallido', 'system', 680, 380, ['Si el ERP no encuentra el NIT, se muestra error de cliente inexistente.', 'Si falla el servicio o la respuesta no es válida, se muestra error y no se permite crear el cliente.']),
      node('create', 'Registrar cliente', 'Respuesta correcta del ERP', 'system', 680, 190, ['Se registra exclusivamente con datos válidos del ERP.', 'No se ofrece un alta manual alternativa ante errores del ERP.']),
      node('client', 'Cliente disponible', 'Existente o registrado desde ERP', 'system', 1020, 0, ['El cliente se reutiliza si ya está en el sistema.', 'Un cliente puede tener uno o varios CSP-Tenants de un mismo proveedor.']),
      node('opportunity', 'Oportunidad · estudio', 'Flujo legado deprecado', 'commercial', 340, -220, ['Se crea una oportunidad, se realizan estudios y, si se aprueba, se convierte en cliente.', 'Esta ruta está deprecada y será retirada.'], { deprecated: true }),
      node('convert', 'Convertir en cliente', 'Solo si el estudio es aprobado', 'commercial', 680, -220, ['Conversión histórica de una oportunidad aprobada.', 'No se añaden condiciones ni estados de estudio no confirmados.'], { deprecated: true }),
      node('tenant', 'Crear CSP-Tenant', 'Comercial · desde nuestro sistema', 'commercial', 1360, 0, ['Pertenece exclusivamente a un cliente y un proveedor; no puede pertenecer a dos clientes.', 'Puede diferenciar segmentos: gobierno, educación, comercial o sin ánimo de lucro; también rangos de facturación y fechas de corte.', 'Se crea como nuevo, existente bajo otro distribuidor o existente creado fuera de la plataforma; el detalle está en el diagrama CSP-Tenant.'], { related: 'csptenant' }),
      node('active', 'CSP-Tenant Activo', 'Condición para utilizarlo en un pedido', 'system', 1700, 0, ['Solo un CSP-Tenant en estado Activo puede usarse en un pedido.', ...priceRules], { related: 'orders' }),
    ],
    edges: [
      edge('nit', 'client', 'Sí · reutilizar'), edge('nit', 'erp-check', 'No'),
      edge('erp-check', 'create', 'Respuesta válida'), edge('erp-check', 'blocked', 'No encontrado / error'),
      edge('create', 'client'), edge('opportunity', 'convert', 'Estudio aprobado', { style: { stroke: '#8899ad', strokeDasharray: '6 5' } }),
      edge('convert', 'client', 'Legado', { style: { stroke: '#8899ad', strokeDasharray: '6 5' } }),
      edge('client', 'tenant', '1 → N'), edge('tenant', 'active', 'Uso en pedidos'),
    ],
  },
  {
    id: 'csptenant', navTitle: 'CSP-Tenant', navSubtitle: 'Creación, estados y traslado',
    title: 'Cada CSP-Tenant nace de un origen y solo se usa Activo',
    description: 'Comercial crea el CSP-Tenant; según su origen pasa por distintos estados hasta que Operaciones lo valida y queda Activo.',
    takeaway: 'Del origen a un CSP-Tenant Activo',
    highlights: [
      'Hay tres orígenes: nuevo, existente bajo otro distribuidor y existente creado fuera de la plataforma. «Nuevo» no es un estado.',
      'En los dos casos existentes, Operaciones consulta si el Tenant está asociado a Controles Empresariales: si lo está queda Activo; si no, se gestiona manualmente.',
      'Solo Operaciones, o el sistema automáticamente, puede inactivar un CSP-Tenant.',
    ],
    nodes: [
      node('entity', 'CSP-Tenant', 'CSP y Tenant, un conjunto inseparable', 'system', 0, -210, [
        'CSP significa cloud solution provider. No existe un CSP sin Tenant ni un Tenant sin CSP.',
        'El Tenant es el intermediario entre la distribución de controles empresariales y el proveedor.',
        'Está asociado a un cliente y tiene relación uno a uno con un CSP.',
        '«Controles Empresariales» es el nombre de la compañía (razón social).',
      ]),
      node('segments', 'Segmentos y subsegmentos', 'Comercial, Educación, Gobierno, Sin ánimo de lucro', 'system', 350, -210, [
        'Segmentos: Comercial, Educación, Gobierno y Sin ánimo de lucro.',
        'Comercial y Sin ánimo de lucro no tienen subsegmentos.',
        'Educación: Sin ánimo de lucro, Educación superior y Colegios.',
        'Gobierno: Federal y Estatal.',
      ]),
      node('contacts', 'Contactos', 'Nombre, correo y teléfono', 'commercial', 700, -210, [
        'Cada contacto tiene nombre, correo y teléfono.',
        'Existe un contacto principal al que el flujo envía las notificaciones.',
      ]),
      node('vendor', 'Funcionalidades por proveedor', 'Suministradas por cada proveedor', 'external', 1050, -210, [
        'Como el Tenant relaciona a Controles Empresariales con cada proveedor, existen funcionalidades propias de cada uno.',
        'El proveedor suministra esa información y es obligatorio integrarla en el sistema.',
        'Compromisos: solo Adobe; permite ver el nivel del contrato o generar un compromiso de compra a 3 años (3YC). Microsoft no lo tiene.',
        'Recomendaciones: solo Adobe; permite ver qué productos son los más viables para la compra.',
      ]),
      node('notes', 'Notas', 'Entidades redundantes y campos sin uso', 'system', 1400, -210, [
        'CSP y Tenant son dos entidades que manejan los mismos estados y actualizaciones. Opción de mejora: unificarlas, por ser redundante usar dos.',
        'Campos como Tipo TRM, Plazo de pago y Prefactura no tienen un uso importante en Multivendor.',
      ]),
      node('create', 'Crear CSP-Tenant', 'Comercial · según el origen', 'commercial', 0, 210, [
        'Comercial lo crea en cualquiera de los tres orígenes.',
        'Nuevo: se crea desde Multivendor porque el cliente no tiene ninguno o quiere abrir uno más; no está asociado a otro distribuidor ni existe fuera de Multivendor. «Nuevo» no es un estado.',
        'Existente bajo otro distribuidor: requiere que el cliente migre a Controles Empresariales.',
        'Existente creado fuera de la plataforma: ya está bajo el dominio de Controles Empresariales.',
      ]),
      node('pending-create', 'Pendiente Creación', 'Origen nuevo · estado inicial', 'system', 350, 0, [
        'Estado inicial del proceso totalmente nuevo, sin traslado entre distribuidores.',
        'Mientras tanto, un servicio Windows registra la solicitud y la procesa de forma automática.',
      ]),
      node('windows', 'Servicio Windows', 'Registra y procesa la solicitud', 'system', 700, 0, [
        'Registra la solicitud y la procesa automáticamente.',
        'Cómo pasa este origen a Activo no está especificado y el visor no lo inventa.',
        'El visor representa este proceso: no lo ejecuta.',
      ]),
      node('pending-invite', 'Pendiente Invitación', 'Antes de la respuesta del cliente', 'system', 350, 210, [
        'Estado intermedio entre la creación y el envío de la solicitud de traslado entre distribuidores.',
        'El cliente recibe la notificación para migrar del distribuidor actual a Controles Empresariales.',
        'Si el cliente rechaza o no responde, el estado nunca cambia: permanece en Pendiente Invitación.',
      ]),
      node('adobe', 'Invitación por Adobe Sign', 'Un webhook escucha la respuesta', 'external', 700, 210, [
        'La notificación se envía mediante Adobe Sign.',
        'Un webhook queda a la escucha de la respuesta del cliente.',
        'El visor representa este proceso: no envía invitaciones.',
      ]),
      node('webhook', 'El cliente acepta', 'Webhook detecta la migración', 'system', 1050, 210, [
        'El usuario acepta la migración.',
        'El webhook detecta que el cliente aceptó el cambio de distribuidor.',
        'El sistema cambia el estado del CSP-Tenant automáticamente.',
      ]),
      node('pending-validate', 'Pendiente Validación Invitación', 'Actualizado por el webhook', 'system', 1400, 210, [
        'Estado que se actualiza automáticamente mediante el webhook al recibir la respuesta del cliente.',
        'Operaciones debe validar si el traslado entre distribuidores fue válido.',
      ]),
      node('followup', 'Seguimiento de Comercial', 'Si el cliente rechaza o no responde', 'commercial', 1050, 430, [
        'Comercial tiene comunicación directa con el cliente.',
        'Debe llamarlo para saber por qué el estado no ha cambiado: si rechazó la invitación o aún no la ha visto.',
        'No hay plazo ni cambio automático de estado.',
      ]),
      node('pending-approval', 'Pendiente Aprobación', 'Existente creado fuera de la plataforma', 'system', 350, 430, [
        'Estado de un CSP-Tenant existente creado fuera de Multivendor.',
        'No se envía solicitud de traslado al cliente, porque ya está bajo el dominio de Controles Empresariales.',
      ]),
      node('notify-ops', 'Notificar a Operaciones', 'Para su validación y activación', 'system', 700, 430, [
        'Al crearse de esta manera, se notifica al área de Operaciones.',
        'Operaciones valida y activa el CSP-Tenant.',
      ]),
      node('validate', 'Validar asociación', 'Operaciones · consulta en Multivendor', 'operations', 1750, 210, [
        'Aplica a los dos orígenes existentes.',
        'Operaciones valida si la transición entre distribuidores fue válida y ejecuta desde Multivendor una consulta para saber si el Tenant está asociado a Controles Empresariales.',
        'Si ya está asociado, el sistema verifica y deja el CSP-Tenant en Activo: es un mismo paso.',
        'Si no está asociado, se muestra un error indicando que el CSP-Tenant no se encontró relacionado.',
        'El visor representa este proceso: no ejecuta la consulta.',
      ]),
      node('error', 'Error · no relacionado', 'Gestión manual', 'operations', 1750, 430, [
        'El CSP-Tenant no se encontró relacionado con Controles Empresariales.',
        'Este caso se debe gestionar de manera manual.',
      ]),
      node('active', 'Activo', 'Pasó por creación y activación', 'system', 2100, 210, [
        'CSP-Tenant que ya pasó por el proceso de creación y activación.',
        'Solo un CSP-Tenant Activo puede usarse en un pedido.',
      ], { related: 'orders' }),
      node('inactive', 'Inactivo', 'Manual o automático', 'operations', 2100, 430, [
        'Se inactiva de forma manual o automática; solo el rol Operaciones o el sistema automáticamente pueden inactivarlo.',
        'Manual: por temas administrativos, por ejemplo falta de pago de las suscripciones.',
        'Automático: otros distribuidores también pueden trasladar un CSP-Tenant; cuando el sistema detecta que ya no está bajo el dominio de Controles Empresariales, lo inactiva.',
      ]),
      node('transfer', 'Traslado entre clientes', 'Un CSP-Tenant ya creado', 'commercial', 2100, 640, [
        'Un CSP-Tenant ya creado puede trasladarse a otro cliente si cumple todas estas condiciones:',
        'El cliente destino está Activo.',
        'El CSP-Tenant a trasladar está Activo.',
        'El cliente se encuentra dentro de la plataforma Multivendor.',
      ]),
      node('deprecated', 'Pendiente Aceptación de términos y condiciones', 'Estado deprecado', 'system', 1750, 640, [
        'Estado deprecado: antes se usaba para formalizar el acuerdo entre el cliente y Controles Empresariales.',
        'No forma parte de ningún flujo vigente.',
      ], { deprecated: true }),
    ],
    edges: [
      edge('create', 'pending-create', 'Nuevo'), edge('create', 'pending-invite', 'Otro distribuidor'),
      edge('create', 'pending-approval', 'Fuera de la plataforma', { sourceHandle: 'bottom' }),
      edge('pending-create', 'windows'),
      edge('windows', 'active', 'Activación no especificada', { targetHandle: 'top', style: { stroke: '#8899ad', strokeDasharray: '6 5' } }),
      edge('pending-invite', 'adobe', 'Notificación'), edge('adobe', 'webhook', 'Respuesta'),
      edge('webhook', 'pending-validate', 'Acepta'),
      edge('adobe', 'followup', 'Sin respuesta o rechazo', { sourceHandle: 'bottom', targetHandle: 'top', style: { stroke: '#8899ad', strokeDasharray: '6 5' } }),
      edge('pending-validate', 'validate', 'Validar'),
      edge('pending-approval', 'notify-ops'), edge('notify-ops', 'validate', 'Validar'),
      edge('validate', 'active', 'Asociado'), edge('validate', 'error', 'No asociado', { sourceHandle: 'bottom', targetHandle: 'top' }),
      edge('active', 'inactive', 'Operaciones o automático', { sourceHandle: 'bottom', targetHandle: 'top', style: { stroke: '#8899ad', strokeDasharray: '6 5' } }),
      edge('active', 'transfer', 'Traslado', { targetHandle: 'top', style: { stroke: '#8899ad', strokeDasharray: '6 5' }, pathOptions: { offset: 60 } }),
    ],
  },
  {
    id: 'products', navTitle: 'Productos', navSubtitle: 'Catálogo, estados y reglas de venta',
    title: 'Solo lo Activo se vende',
    description: 'Los productos del proveedor se sincronizan cada día; su estado y segmento determinan si pueden agregarse a un pedido.',
    takeaway: 'Del catálogo del proveedor al pedido',
    highlights: [
      'La sincronización diaria actualiza lo que existe, crea lo nuevo como Inconsistente e inactiva lo que ya no viene en la lista.',
      'Un Administrador clasifica los productos Inconsistentes; después quedan Activos.',
      'Solo se venden productos Activos y del mismo segmento del CSP-Tenant.',
    ],
    nodes: [
      node('product', 'Producto', 'Costo, precio sugerido y segmento', 'system', 0, -210, ['Costo fabricante y precio máximo sugerido.', 'Segmentos: Comercial, Educación y Gobierno.', 'Código proveedor suministrado por el proveedor.', 'Términos de duración y ciclos de facturación.', 'Cada producto guarda su fecha de actualización: la de su creación o última actualización.']),
      node('code', 'Código interno', 'Calculado por el sistema', 'system', 350, -210, ['Se forma concatenando código proveedor, segmento, término de facturación y duración. Ejemplo: 65324789CA13A12:0-Comercial-Anual-P3Y.', 'Garantiza códigos únicos: el proveedor repite el mismo código, pero los costos varían según término de duración y segmento.']),
      node('types', 'Tipos de producto', 'Según el proveedor', 'external', 700, -210, ['Trial: productos de prueba que por lo general no tienen costo ni precio máximo sugerido.', 'Costo Cero: complementos de otros productos, sin valor.', 'Introductorios: precio especial, fuera de la lista regular y solo para ventas autorizadas.']),
      node('provider', 'Listas de precios', 'Proveedor · por segmento o tipo', 'external', 0, 0, ['Un proveedor puede tener varias listas de precios, separadas por segmento o tipo de producto.', 'Se consultan por API, por proveedor y por segmento.']),
      node('service', 'Servicio diario', 'Windows · todos los días ~2 a. m.', 'system', 350, 0, ['Se ejecuta todos los días sobre las 2 a. m.', 'Consulta el listado de productos por API, por cada proveedor y cada segmento.', 'El visor representa este proceso: no lo ejecuta.']),
      node('csv', 'Archivos CSV', 'Uno por lista de precios', 'system', 700, 0, ['Construye un archivo CSV con la información suministrada por el API para cada lista.', 'Dentro del mismo servicio se lee y procesa cada archivo; al terminar de procesarlo, se borra.']),
      node('verify', 'Verificar línea por línea', '¿El producto ya existe?', 'system', 1050, 0, ['Si existe, se actualiza: nombre, descripción, precio, etc., y su fecha de actualización.', 'Si no existe, se crea en estado Inconsistente.', 'Un producto Inactivo o Descontinuado que reaparece en la lista vuelve a Activo.']),
      node('active', 'Activo', 'Listo para agregar al pedido', 'system', 1400, 0, ['Producto listo para ser agregado a un pedido.', 'Puede pasar a Inactivo o a Descontinuado de forma manual.']),
      node('sale', 'Reglas de venta', 'Estado, segmento y márgenes', 'commercial', 1750, 0, [
        'Para agregarse a un pedido debe estar Activo.',
        'Solo se venden productos del mismo segmento del CSP-Tenant: un producto Comercial no se vende a un CSP-Tenant de Educación.',
        'Los márgenes de utilidad se parametrizan por producto.',
        'Sin márgenes parametrizados, el sistema calcula el margen entre costo fabricante y precio máximo sugerido; la fórmula no fue especificada y este visor no la inventa.',
        'Un parámetro por proveedor, si está habilitado, impide continuar el pedido cuando costo fabricante + margen de utilidad parametrizado supera el precio máximo sugerido: algunos proveedores multan a los distribuidores que lo exceden.',
      ], { related: 'orders' }),
      node('inactivate', 'Inactivar no vistos', 'Al procesar todos los archivos', 'system', 350, 430, ['Solo se inactivan los productos Activos con fecha de actualización anterior a la fecha de ejecución del servicio.', 'Se entiende que ya no vienen en la lista de precios y no están disponibles para la venta.']),
      node('inactive', 'Inactivo', 'Fuera de la lista o inactivado a mano', 'system', 700, 430, ['Ya no está en la lista de precios actual o fue inactivado manualmente por alguna razón.', 'No puede agregarse a un pedido.', 'Si reaparece en la lista durante la sincronización, vuelve a Activo.']),
      node('inconsistent', 'Inconsistente', 'Creado por la sincronización', 'system', 1050, 430, ['No existía antes en la base de datos: se creó al actualizar las listas.', 'El servicio no puede categorizarlo correctamente por su clasificación, por lo que requiere un ajuste manual.']),
      node('classify', 'Clasificar producto', 'Administrador · ajuste manual', 'admin', 1400, 430, ['Se requiere ayuda humana para ingresar al producto y clasificarlo correctamente.', 'Al guardarlo clasificado, queda en estado Activo.']),
      node('discontinued', 'Descontinuado', 'Asignado manualmente', 'system', 1750, 430, ['Ya no viene en la lista de precios, pero se mantiene por clientes con suscripciones activas.', 'No se permite en ventas nuevas.', 'Solo se vende a clientes con suscripción activa que usen la renovación; si la dejan vencer, ya no puede venderse.', 'Si reaparece en la lista durante la sincronización, vuelve a Activo.']),
      node('failure', 'Fallo de actualización', 'Notificación a operaciones', 'operations', 0, 430, ['Si falla algún proceso de actualización de precios, se notifica al buzón de operaciones parametrizado en base de datos.']),
    ],
    edges: [
      edge('types', 'product', 'Según proveedor'), edge('product', 'code', 'Compone'),
      edge('provider', 'service', 'API'), edge('service', 'csv', 'Un CSV por lista'), edge('csv', 'verify', 'Procesar'),
      edge('verify', 'active', 'Existe · actualiza'),
      edge('verify', 'inconsistent', 'No existe', { sourceHandle: 'bottom', targetHandle: 'top' }),
      edge('inconsistent', 'classify'),
      edge('classify', 'active', 'Clasificado', { sourceHandle: 'bottom', targetHandle: 'top' }),
      edge('csv', 'inactivate', 'Al terminar', { sourceHandle: 'bottom', targetHandle: 'top' }),
      edge('inactivate', 'inactive', 'No vistos'),
      edge('active', 'inactive', 'Inactivación manual', { sourceHandle: 'bottom', targetHandle: 'top', style: { stroke: '#8899ad', strokeDasharray: '6 5' }, pathOptions: { offset: 40 } }),
      edge('inactive', 'active', 'Reaparece en la lista', { sourceHandle: 'bottom', targetHandle: 'top', style: { stroke: '#8899ad', strokeDasharray: '6 5' }, pathOptions: { offset: 70 } }),
      edge('active', 'discontinued', 'Asignación manual', { style: { stroke: '#8899ad', strokeDasharray: '6 5' } }),
      edge('discontinued', 'active', 'Reaparece en la lista', { sourceHandle: 'bottom', targetHandle: 'top', style: { stroke: '#8899ad', strokeDasharray: '6 5' }, pathOptions: { offset: 40 } }),
      edge('active', 'sale', 'Activo'),
      edge('discontinued', 'sale', 'Solo renovación', { sourceHandle: 'bottom', targetHandle: 'top' }),
      edge('service', 'failure', 'Si falla', { sourceHandle: 'bottom', targetHandle: 'top' }),
    ],
  },
  {
    id: 'orders', navTitle: 'Pedido & aprobaciones', navSubtitle: 'Márgenes, documentos y controles',
    title: 'Vender con control, aprobar con criterio',
    description: 'El margen se evalúa sobre todo el pedido. Gerencia resuelve excepciones y Operaciones verifica los soportes.',
    takeaway: 'Dos controles, responsabilidades distintas',
    highlights: ['Solo márgenes globales por debajo de algún mínimo requieren aprobación. La igualdad no la requiere.', 'Documentos faltantes bloquean el avance con un mensaje de error.', 'El rechazo de Gerencia conserva el estado; Devuelto corresponde al retorno de Operaciones.'],
    nodes: [
      node('prepare', 'Alistamiento', 'Comercial prepara y guarda el pedido', 'commercial', 0, 0, [...orderRules, 'Comercial agrega productos, configura márgenes y adjunta los documentos obligatorios.']),
      node('margin', 'Verificación de márgenes', 'Evaluación ponderada / global del pedido', 'system', 350, 0, [...priceRules, 'Se comparan los márgenes globales de servicios y utilidad con los mínimos configurables por proveedor.', 'Si cualquiera queda por debajo, se requiere aprobación de Gerencia. Si ambos igualan o superan los mínimos, no se requiere.', 'La fórmula exacta y los pesos del ponderado global no fueron especificados; este visor no inventa un cálculo ni evalúa líneas individualmente.']),
      node('management', 'Aprobación de Gerencia', 'Excepción de margen dentro del sistema', 'management', 700, 220, ['Gerencia estudia si los márgenes globales son adecuados para el negocio y aprueba dentro del sistema.', 'Operaciones no puede aprobar un pedido con aprobación requerida pendiente o rechazada.']),
      node('adjust', 'Ajustar según observaciones', 'Comercial corrige · conserva el estado', 'commercial', 350, 430, ['Si Gerencia rechaza, el pedido mantiene su estado y Comercial ajusta según sus observaciones.', 'Se vuelve a verificar si el pedido ajustado necesita aprobación.', 'No se crea un estado adicional de rechazo.']),
      node('documents', 'Documentos completos', 'Control antes de ingresar a Operaciones', 'system', 1050, 0, ['Comercial debe adjuntar documentos obligatorios antes de la revisión de Operaciones.', 'Los documentos requeridos son iguales para todos los proveedores; no se inventa una lista de tipos.']),
      node('missing', 'Avance bloqueado · error', 'Faltan documentos obligatorios', 'system', 1050, 430, ['Se muestra un mensaje indicando que no puede continuar porque faltan documentos.', 'Comercial completa los adjuntos antes de intentar avanzar de nuevo.']),
      node('operations', 'Pendiente Validar Operaciones', 'Contrastar pedido y documentos adjuntos', 'operations', 1400, 0, ['Operaciones valida productos, cantidades, costos y precios finales contra los documentos.', 'Todo debe coincidir. Operaciones no crea ni aprueba solicitudes de margen.', 'Solo se llega aquí sin requerir aprobación de margen o con aprobación de Gerencia obtenida.']),
      node('returned', 'Devuelto', 'Operaciones retorna a Comercial', 'operations', 1400, 430, ['Comercial corrige costos, cantidades, productos u otros datos observados.', 'Tras corregir se repiten los controles aplicables de márgenes y documentos.']),
      node('ready', 'Por Aplicar', 'Operaciones validó el pedido', 'system', 1750, 0, ['La aprobación de Operaciones no significa que el pedido esté aprovisionado.', 'Queda disponible para el servicio background de aprovisionamiento.'], { related: 'provisioning' }),
    ],
    edges: [
      edge('prepare', 'margin'), edge('margin', 'management', 'Algún margen < mínimo'),
      edge('margin', 'documents', 'Ambos ≥ mínimos'), edge('management', 'documents', 'Aprobado'),
      edge('management', 'adjust', 'Rechazado', { sourceHandle: 'bottom', targetHandle: 'top' }),
      edge('adjust', 'margin', 'Reevaluar', { sourceHandle: 'bottom', targetHandle: 'top' }),
      edge('documents', 'operations', 'Sí'), edge('documents', 'missing', 'No', { sourceHandle: 'bottom', targetHandle: 'top' }),
      edge('missing', 'documents', 'Completar adjuntos', { sourceHandle: 'bottom', targetHandle: 'top' }),
      edge('operations', 'ready', 'Coincide · aprobado'), edge('operations', 'returned', 'No coincide', { sourceHandle: 'bottom', targetHandle: 'top' }),
      edge('returned', 'prepare', 'Correcciones', { sourceHandle: 'bottom', targetHandle: 'top' }),
    ],
  },
  {
    id: 'provisioning', navTitle: 'Aprovisionamiento', navSubtitle: 'Compras por CSP y resultados',
    title: 'Cada CSP-Tenant, una compra independiente',
    description: 'Un servicio background divide el pedido por CSP-Tenant y consolida los resultados de las compras.',
    takeaway: 'Reintentar sin duplicar lo entregado',
    highlights: ['Las compras siempre corresponden al único proveedor del pedido.', 'Aprovisionado significa que todo se completó correctamente.', 'En Aplicado Parcial solo se ajustan y reintentan los elementos no aprovisionados.'],
    nodes: [
      node('ready', 'Por Aplicar', 'Pedido validado por Operaciones', 'system', 0, 0, ['Punto de entrada del aprovisionamiento automático.', 'Pedido de un único cliente y proveedor, con uno o varios CSP-Tenants.'], { related: 'orders' }),
      node('split', 'Separar por CSP-Tenant', 'Servicio background', 'system', 350, 0, ['Agrupa los productos del pedido según su CSP-Tenant, no según el cliente.', 'Genera las compras correspondientes a cada CSP-Tenant del pedido.']),
      node('purchase', 'Comprar en el proveedor', 'Intento por cada CSP-Tenant', 'external', 700, 0, ['Para el proveedor, el CSP-Tenant identifica al cliente de la compra.', 'Todos los intentos corresponden al mismo proveedor; el pedido nunca mezcla proveedores.']),
      node('result', 'Consolidar resultados', 'Éxito total, fallo total o parcial', 'system', 1050, 0, ['El resultado conjunto determina el estado del pedido.', 'No se considera terminado al aprobar Operaciones ni al iniciar las compras.']),
      node('success', 'Aprovisionado', 'Todos los intentos fueron exitosos', 'system', 1400, -210, ['El pedido se considera terminado en este estado.', 'Los detalles de suscripciones se sincronizan bajo demanda al entrar al CSP-Tenant.'], { related: 'subscriptions' }),
      node('error', 'Error Envio', 'Todos los intentos fallaron', 'system', 1400, 0, ['No hubo compras exitosas.', 'No se especificó una política de reintentos automáticos para fallo total; no se inventa.']),
      node('partial', 'Aplicado Parcial', 'Algunos éxitos y algunos fallos', 'system', 1400, 210, ['Se conservan los elementos que ya fueron aprovisionados.', 'Comercial revisa por qué fallaron los elementos con Error Envio.']),
      node('retry', 'Revisar, ajustar y reintentar', 'Comercial · solo no aprovisionados', 'commercial', 1050, 430, ['Comercial revisa los fallos y ajusta los productos no aprovisionados.', 'Solo esos elementos se envían nuevamente al aprovisionamiento, agrupados por CSP-Tenant.', 'Los elementos ya aprovisionados no se compran de nuevo.', 'El resultado consolidado tiene en cuenta los éxitos anteriores y los nuevos intentos.']),
    ],
    edges: [
      edge('ready', 'split'), edge('split', 'purchase', 'Por CSP'), edge('purchase', 'result', 'Resultados'),
      edge('result', 'success', 'Todos exitosos'), edge('result', 'error', 'Todos fallidos'),
      edge('result', 'partial', 'Éxitos + fallos'),
      edge('partial', 'retry', 'Revisar fallos', { sourceHandle: 'bottom', targetHandle: 'top' }),
      edge('retry', 'split', 'Solo pendientes', { sourceHandle: 'bottom', targetHandle: 'top' }),
    ],
  },
  {
    id: 'subscriptions', navTitle: 'Suscripciones', navSubtitle: 'Consulta bajo demanda y contactos',
    title: 'El detalle actualizado, cuando lo necesitas',
    description: 'Entrar al detalle del CSP-Tenant dispara la sincronización de suscripciones. Los contactos son informativos.',
    takeaway: 'Consulta local, datos del proveedor',
    highlights: ['La sincronización es bajo demanda, no una tarea periódica del catálogo.', 'El detalle incluye cantidades, fechas de inicio y fin.', 'Los contactos pertenecen al CSP-Tenant y no intervienen en las aprobaciones.'],
    nodes: [
      node('client', 'Cliente', 'Seleccionar su CSP-Tenant', 'commercial', 0, 0, ['Un cliente puede tener varios CSP-Tenants de un mismo proveedor.', 'Cada CSP-Tenant es exclusivo de ese cliente y proveedor.'], { related: 'lifecycle' }),
      node('detail', 'Entrar al detalle del CSP', 'Disparador de sincronización bajo demanda', 'system', 350, 0, ['Al entrar a este detalle se sincronizan las suscripciones.', 'El visor representa este proceso: no ejecuta consultas reales a proveedores.']),
      node('provider', 'Consultar proveedor', 'Suscripciones del CSP-Tenant', 'external', 700, 0, ['Se solicitan los detalles asociados a ese CSP-Tenant.', 'No se afirma que haya una sincronización periódica adicional.']),
      node('sync', 'Sincronizar suscripciones', 'Actualizar información para consulta', 'system', 1050, 0, ['Actualiza el detalle al ingresar al CSP-Tenant.', 'La sincronización de suscripciones es distinta de la actualización automática del catálogo.']),
      node('subscriptions', 'Consultar detalle', 'Cantidades · fecha de inicio · fecha de fin', 'commercial', 1400, 0, ['Permite consultar suscripciones y sus detalles.', 'Los pedidos sobre suscripciones activas pueden modificar cantidades o cancelar, entre otras operaciones mencionadas.', 'No se definen aquí operaciones adicionales ni políticas para suscripciones vencidas o suspendidas.']),
      node('contacts', 'Contactos del CSP-Tenant', 'Datos de referencia ante dudas', 'commercial', 700, 260, ['Son contactos del CSP-Tenant, no del pedido ni compartidos entre clientes.', 'Son informativos y no autorizan compras, márgenes o aprovisionamientos.']),
      node('order', 'Pedido sobre suscripciones', 'Sin mezclar con productos nuevos', 'commercial', 1400, 260, orderRules, { related: 'orders' }),
    ],
    edges: [
      edge('client', 'detail'), edge('detail', 'provider', 'Al ingresar'), edge('provider', 'sync', 'Datos'),
      edge('sync', 'subscriptions'), edge('detail', 'contacts', 'Información', { sourceHandle: 'bottom', targetHandle: 'top' }),
      edge('subscriptions', 'order', 'Flujo relacionado', { sourceHandle: 'bottom', targetHandle: 'top' }),
    ],
  },
]
